### ISSUE TITLE
Couldn't find Corvis in UCLA-Vision website

### ISSUE THREAD

**Issue by qh-huang** [ucla-vision/xivo#12]
I'm very interested in this work and wanted to know more. However, the documentation keep mentioning "Corvis", which I can only find the paper but not the source code anymore. Is the project closed?

**Comment by stephanietsuei** [comment]
Yes, Corvis is closed and we've chosen to take it off the Internet. Please consider Xivo the replacement of Corvis. We haven't gotten around to implementing loop closure yet, but everything else is the same.

**Comment by qh-huang** [comment]
Understand. Thanks for the answer.
