### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by Xuechun-Hu** [ucla-vision/xivo#13]
![选区_629](https://user-images.githubusercontent.com/21210381/70842423-752f1380-1e5e-11ea-9787-ef400697c564.png)
Hi  can you provide this dataset? thanks!

**Comment by stephanietsuei** [comment]
We're working on it; it'll be released in conjunction with another paper. I'll post here again once it's up.

**Comment by stephanietsuei** [comment]
Dataset is here: https://github.com/alexklwong/void-dataset
