### ISSUE TITLE
Question: How does it deal with the observability issues?

### ISSUE THREAD

**Issue by Edwinem** [ucla-vision/xivo#14]
More a confirmation question.

So I have been digging through the code, and through the papers, and was wondering how XIVO deals with the observability issues noted in many of your past papers, and also by the work of University of Minnesota under Stergios. I know in Minnesota's MSCKF work they either use the Observability Constrained approach(projects the Jacobians on to the observable subspace), or uses First Estimate Jacobians(FEJ).

My best guess right now is that it is handled somehow through smartly dealing with the gauge freedom(still need to figure this out).

**Comment by stephanietsuei** [comment]
How Xivo deals with observability issues is described in detail in the 2010 paper "Visual–inertial navigation, mapping and localization: A scalable real-time causal approach" by Jones and Soatto. (Consider Xivo a rewrite of the software Corvis described in that paper). In short,

1. At initialization, the initial pose (R0, T0) is fixed to (Identity, Zero).
2. At each timestep, all observed features are collected into a "group", labeled with the current pose estimate (Rsb, Tsb)_i. These groups are part of the estimated state. At any given time, the pose of one of these groups (called the "reference group") is fixed. When the reference group is lost, another group is chosen as the reference.
