### ISSUE TITLE
How to generate sparse depth maps from XIVO?

### ISSUE THREAD

**Issue by mikkeljakobsen** [ucla-vision/xivo#18]
I'm trying to save the tracked feature points in order to generate sparse depth maps like your recently published Visual Inertial Odometry Dataset (VOID): https://github.com/alexklwong/void-dataset

The sparse depth maps in the dataset are generated by XIVO by tracking 150, 500 and 1500 feature points respectively.

I've managed to save all tracked features (including out-of-state features), but I only get 50-200 points per frame from XIVO even though I've increased tracker_cfg:num_features_max and memory:max_features in the configuration file.

What else do I need to do in order to increase the amount of features tracked? And can you maybe share the configuration file used for generating the VOID dataset?

Best regards, Mikkel

**Comment by feixh** [comment]
> I'm trying to save the tracked feature points in order to generate sparse depth maps like your recently published Visual Inertial Odometry Dataset (VOID): https://github.com/alexklwong/void-dataset
> 
> The sparse depth maps in the dataset are generated by XIVO by tracking 150, 500 and 1500 feature points respectively.
> 
> I've managed to save all tracked features (including out-of-state features), but I only get 50-200 points per frame from XIVO even though I've increased tracker_cfg:num_features_max and memory:max_features in the configuration file.
> 
> What else do I need to do in order to increase the amount of features tracked? And can you maybe share the configuration file used for generating the VOID dataset?
> 
> Best regards, Mikkel

The sparse depth maps were generated by an internal and experimental version of XIVO.
You can either use the sparse depth maps provided by the VOID dataset or obtain such sparse point clouds in a post processing step, i.e., track more features given the video and triangulate them given the pose estimates from XIVO, etc.

**Comment by hjxwhy** [comment]
> I'm trying to save the tracked feature points in order to generate sparse depth maps like your recently published Visual Inertial Odometry Dataset (VOID): https://github.com/alexklwong/void-dataset
> 
> The sparse depth maps in the dataset are generated by XIVO by tracking 150, 500 and 1500 feature points respectively.
> 
> I've managed to save all tracked features (including out-of-state features), but I only get 50-200 points per frame from XIVO even though I've increased tracker_cfg:num_features_max and memory:max_features in the configuration file.
> 
> What else do I need to do in order to increase the amount of features tracked? And can you maybe share the configuration file used for generating the VOID dataset?
> 
> Best regards, Mikkel

hello, do you know how to read raw data in VOID, the features saved in raw data are XYZ data struct?

**Comment by alexklwong** [comment]
This is now answered in 
https://github.com/alexklwong/void-dataset/issues/5
