### ISSUE TITLE
Estimated sparse depth is wrong

### ISSUE THREAD

**Issue by mikkeljakobsen** [ucla-vision/xivo#19]
Hi,

I've been working a lot with this project for my master thesis, and I've managed to successfully apply it to my own custom IMU-enabled camera. I'm also able to extract sparse depth maps from XIVO. 

I believe my calibration of the camera and IMU is correct, however, the quality of the extracted sparse depth maps are not good enough. My camera captures depth as well, and when I compare these ground truth values to the estimated sparse depth from XIVO, the estimates are on average 20% off relative to ground truth. Tried to adjust sub-filter settings and other stuff but I haven't managed to lower this error.

Do you have any suggestions on what could be causing this error? And possibly what can be done to improve the estimates?

Kind regards, Mikkel

**Comment by stephanietsuei** [comment]
Hi Mikkel,

I'm not surprised at all that you're seeing this. We have mainly focused on localization accuracy and not mapping accuracy, and we have never benchmarked the mapping accuracy. When features are initialized into the subfilter, they all get the same initial depth (`initial_z` in the configuration files) - the subfilter (and triangulation, if it is enabled) adjust them each to the right value over time. If you plot the location of feature estimates over time, you'll notice that they drift and change over time. Also, we haven't yet implemented any loop closure algorithms.

If your project is mainly postprocessing you can also try taking the average of all estimated locations for each feature, and see if that increases accuracy. If your project is something that must be run online, then my best guess says that

1. feature position accuracy increases with time
2. you might get better results if you increase the amount of time the feature must stay in the subfilter before going into the main filter (`subfilter.ready_steps`)

If mapping accuracy is an important part of your master's project, then you might be better off using a (nonlinear/nonconvex) optimization-based (as opposed to filtering-based) SLAM. The tradeoff is computational cost - XIVO will be much faster.

Best,
Stephanie

**Comment by mikkeljakobsen** [comment]
Hi Stephanie,

Thanks for your answer. That was really helpful!

I've tried to keep track of the feature ID's to see how their positions gets updated. As far as I understand "f->Xs" is the position in the spatial frame. And "f->Xc" is the position wrt the camera (which is what I need), but it's always from the current camera view. How do I map it to the frame where it was first discovered? Do I need to use the poses?

Best regards, Mikkel

**Comment by stephanietsuei** [comment]
Hi,

We don't store the position of each feature with respect to every single past pose, so you will need to do some data processing. But here's what we do store:

1. The estimated position of every single past pose, also known as a "group", in the inertial frame. These past estimates are updated over time, though.

2. Every single observation (pixel x, pixel y) of the feature. If you look at feature.cpp, you'll see that `Feature` inherits from `Track`, which inherits from `std::vector<Vec2>`. So you can actually just use standard C++ vector manipulation to get old pixel observations.

Best,
Stephanie

**Comment by mikkeljakobsen** [comment]
Thanks again. 

My project is mainly for online processing. The end goal is to deploy it on a mobile robot that should be able to estimate true dense depth in real-time given a monocular camera and an IMU. 

I was hoping that the feature positions were saved allowing for "sampling" the updated sparse depth maps just a few frames later. My deadline is approaching so I needed a quick fix ;) And I don't think I'm able to implement your nice suggestions for data processing.

But thanks a lot for your time :)

**Comment by stephanietsuei** [comment]
@mikkeljakobsen  - that sounds very interesting! Good luck on your project. We're always interested in what people are doing with our work.
