### ISSUE TITLE
Cmake error from Pangolin when run build.sh

### ISSUE THREAD

**Issue by duyanwei** [ucla-vision/xivo#21]
# ISSUE

CMake complains that 

```
-- Checking for module 'xkbcommon'
--   No package 'xkbcommon' found
```

when running `./build.sh`

# Solution

It seems to be a bug in Pangolin, and they already have it fixed. 

https://github.com/stevenlovegrove/Pangolin/pull/565

It would be great if you can update it accordingly.

**Comment by stephanietsuei** [comment]
Done. Pangolin was updated to the latest release in #27.
