### ISSUE TITLE
Rodrigues Unit Tests Fail

### ISSUE THREAD

**Issue by stephanietsuei** [ucla-vision/xivo#48]
Some unit tests in `src/test/test_rodrigues.cpp` are failing. Problems may exist either in the unit tests or the `common/rodrigues.h`.

For the tests checking Jacobians, we should switch to checking individual elements of the Jacobian matrix (as is done in `src/test/unittest_rodrigues.cpp`) rather than just testing the norm.

**Comment by agrawalparth10** [comment]
Addressed in #54
