### ISSUE TITLE
Error building with ROS

### ISSUE THREAD

**Issue by tekrajchhetri** [ucla-vision/xivo#5]
I was able to build without ros node but when I try with ros node, its failing.

![Screenshot from 2019-10-22 15-45-31](https://user-images.githubusercontent.com/52251022/67287994-cff26180-f4e4-11e9-83d2-ddf61662a089.png)

**Comment by stephanietsuei** [comment]
That error doesn't look familiar to me. What version of ROS and Python are you using? We have really only tested xivo using ROS Kinetic.

**Comment by tekrajchhetri** [comment]
@stephanietsuei it's Ubuntu 18 with ROS  melodic and python 2.

**Comment by stephanietsuei** [comment]
I think I reproduced the error on our end. For now, please build with both g2o and ROS: `./build.sh ros g2o`.

**Comment by tekrajchhetri** [comment]
@stephanietsuei Thank you. I am now able to build with ROS. Also, a suggestion, it is better to specify the version of opencv and other tools used because if it is the latest version then not all methods might be available with the older versions. I had similar issue with opencv for which I had to check the source to figure out what was wrong. Any way thanks again.
