### ISSUE TITLE
Realsense Configuration

### ISSUE THREAD

**Issue by JeremyBYU** [ucla-vision/xivo#7]
Hi,
Thanks for releasing the source code for this project. I was wondering if you have the configuration files for the Realsense D435i as shown in the `README.md` gif. It seems the demos that you provide in `wiki.md` have to do with Tango enabled phones.  Not knowing the algorithm well I was thinking these settings in `phab.json` would need to change:

```json
{

  "imu_calib": {
  },
  "camera_cfg": {
  }
}
```

In the meantime I will look over the papers to see if can make some of the these parameters. Thanks!

**Comment by stephanietsuei** [comment]
Hi,

Yes, you are correct. XIVO is a new project and we've only released data and the corresponding calibration for Tango phones so far. To use a different sensor, `imu_calib` and `camera_cfg` are the settings that would need to change. 

If you're looking to use your own RealSense, though, you'll probably want to calibrate it yourself using something like the [Kalibr Toolbox](https://github.com/ethz-asl/kalibr). Any numbers I post here are only really applicable to data that we collect.

**Comment by JeremyBYU** [comment]
Thanks.  Looks like the D435i extrinsics are already calculated per the [device](https://www.intelrealsense.com/how-to-getting-imu-data-from-d435i-and-t265/). But the IMU intrinsic need to be calibrated (with their tool or maybe Kalibr):

> For D435i the IMU sensor is not calibrated, hence a free calibration tool is available as as part of the SDK. Running the calibration routine will calculate IMU intrinsic covariance and zero offsets, and then store them on device’s NVRAM for later use in SDK. **The depth<->IMU sensor extrinsic (rigid body transformation) is precalculated based on mechanical drawings and cannot be modified**. When initialized, the SDK will query the device for the existence of the IMU calibration data, and if present – apply it to the raw IMU samples produced by the device.

Sp I think that means the IMU extrinsics input to your estimator are supposed to be 0 basically (no rot, no translation). However the camera model seems to be different (Brown Conrady, vs equidistant). So maybe I will need to get the intrinsic of that model through Kalibr or some other tool. 

One thing that would be helpful is some documentation on the parameters. Some of them seem to be obvious but others I'm not so sure about! Thanks for your quick response and help!

Somewhat useful links for myself and others:

- [ Realense with Kalibr ](https://www.cnblogs.com/williamc17/p/10797677.html)
- [Realsense with VinsFusion](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/issues/36)
- [Success with Relasense and Vin Fusion](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/issues/6) - Looks like they got it to succeed using the intrinsic parameters read straight from the camera. They used  roughly calibrated extrinsic parameters and then let Vins estimate the rest.
