### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by tekrajchhetri** [ucla-vision/xivo#8]
Hi, @stephanietsuei xivo is really fast and also takes GPU for processing if available (ran with OpenCV 4.). And thanks for the release of code. Based on my testing I find that it only supports one camera topic input along with IMU. My question is, are there any future plans for stereo support or if already present, could you provide information to run in stereo mode? 

-Thanks

**Comment by stephanietsuei** [comment]
Sorry, there is currently no implementation for stereo available and no plans to support it.
