### ISSUE TITLE
Xivo and Twilio

### ISSUE THREAD

**Issue by LinuxDevSecOps** [ucla-vision/xivo#9]
Hello,
I am facing some problems with xivo connecting with Twilio Trunk. Can someone suggest how to configure xivo for Twilio SIP provider. I tried with the DOCS of xivo . But there I am confused about outgoing and incoming call. Here some details:

username: VOIPSERVER
password: RJEKVtTntG8P4VHV92YU
Server . fourthestate.pstn.twilio.com
phone: +12028732400
(202) 873-2400
Extension:
7101 for me
7900 for a test user.

Can someone give me any source so that I can configure or implement twilio on Xivo IP-PBX asterisk.

I also attached files so that you can understand clearly. Please if possible it will be more helpful if you can help as soon.
![tw04](https://user-images.githubusercontent.com/48767068/68069265-2767bb80-fd88-11e9-9504-4b7906fd2bd7.PNG)
![tw03](https://user-images.githubusercontent.com/48767068/68069267-2767bb80-fd88-11e9-96cd-c6e5915c553f.PNG)
![tw02](https://user-images.githubusercontent.com/48767068/68069268-2767bb80-fd88-11e9-9c33-6adc080eac40.PNG)
![tw01](https://user-images.githubusercontent.com/48767068/68069269-28005200-fd88-11e9-9e7d-4478e2a3fbad.PNG)

Thanks

**Comment by feixh** [comment]
Hi @LinuxDevSecOps, it happens that our repo has exactly the same name as a popular VoIP repo XIVO. But I think our repo is not what you are actually looking for.
